# Generated by Django 5.2.4 on 2025-07-09 09:30

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import ekspedisi_app.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='JenisLayanan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nama_layanan', models.CharField(max_length=100)),
                ('deskripsi', models.TextField()),
                ('tarif_per_kg', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'Jenis Layanan',
                'verbose_name_plural': 'Jenis Layanan',
            },
        ),
        migrations.CreateModel(
            name='Penerima',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nama_penerima', models.CharField(max_length=255)),
                ('alamat_penerima', models.TextField()),
                ('nomor_telepon_penerima', models.CharField(max_length=20)),
                ('kota_tujuan', models.CharField(max_length=100)),
                ('kode_pos', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Penerima',
                'verbose_name_plural': 'Penerima',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('staf', 'Staf'), ('kurir', 'Kurir'), ('pelanggan', 'Pelanggan')], default='pelanggan', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Pengiriman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nomor_resi', models.CharField(default=ekspedisi_app.models.increment_resi_number, max_length=20, unique=True)),
                ('tanggal_pengiriman', models.DateTimeField(default=django.utils.timezone.now)),
                ('status_pengiriman', models.CharField(choices=[('pending', 'Pending'), ('pickup', 'Pickup'), ('transit', 'Transit'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('total_berat', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_biaya', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('catatan', models.TextField(blank=True, null=True)),
                ('jenis_layanan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ekspedisi_app.jenislayanan')),
                ('kurir', models.ForeignKey(blank=True, limit_choices_to={'role': 'kurir'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pengiriman_kurir', to=settings.AUTH_USER_MODEL)),
                ('pengirim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pengiriman_pengirim', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pengiriman',
                'verbose_name_plural': 'Pengiriman',
                'ordering': ['-tanggal_pengiriman'],
            },
        ),
        migrations.CreateModel(
            name='Paket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kode_paket', models.CharField(default=ekspedisi_app.models.increment_paket_code, max_length=20, unique=True)),
                ('nama_barang', models.CharField(max_length=255)),
                ('deskripsi_barang', models.TextField()),
                ('berat', models.DecimalField(decimal_places=2, max_digits=10)),
                ('panjang', models.DecimalField(decimal_places=2, max_digits=10)),
                ('lebar', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tinggi', models.DecimalField(decimal_places=2, max_digits=10)),
                ('jenis_paket', models.CharField(choices=[('kecil', 'Paket Kecil'), ('kargo', 'Kargo')], default='kecil', max_length=20)),
                ('nilai_barang', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('asuransi', models.BooleanField(default=False)),
                ('foto_paket', models.ImageField(blank=True, null=True, upload_to='paket_pics/')),
                ('penerima', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ekspedisi_app.penerima')),
                ('pengiriman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paket_set', to='ekspedisi_app.pengiriman')),
            ],
            options={
                'verbose_name': 'Paket',
                'verbose_name_plural': 'Paket',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nama_lengkap', models.CharField(max_length=255)),
                ('alamat', models.TextField()),
                ('nomor_telepon', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('foto_profil', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RiwayatPengiriman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(max_length=100)),
                ('keterangan', models.TextField()),
                ('lokasi', models.CharField(max_length=255)),
                ('waktu', models.DateTimeField(default=django.utils.timezone.now)),
                ('pengiriman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='riwayat_pengiriman', to='ekspedisi_app.pengiriman')),
            ],
            options={
                'verbose_name': 'Riwayat Pengiriman',
                'verbose_name_plural': 'Riwayat Pengiriman',
                'ordering': ['-waktu'],
            },
        ),
    ]
